AdminManagement/urls.py
from django.urls import path
from .views import (
    ErrorErrorView,
    ErrorView,
    LugarErrorView,
    ParqueCreateView,
    ParqueListView,
    ParqueDetailView,
    ParqueUpdateView,
    ParqueDeleteView,
    ZonaErrorView,
    ZonaListView,
    ZonaDeleteView,
    ZonaCreateView,
    ZonaDetailView,
    ZonaUpdateView,
    LugarListView,
    LugarCreateView,
    LugarDetailView,
    LugarDeleteView,
    LugarUpdateView,
)

app_name = 'AdminManagement'
urlpatterns = [
    path('', ParqueListView.as_view(), name='parque-list'),
    path('<int:id>/', ParqueDetailView.as_view(), name='parque-detail'),
    path('create/', ParqueCreateView.as_view(), name='parque-create'),
    path('<int:id>/update/', ParqueUpdateView.as_view(), name='parque-update'),
    path('<int:id>/delete/', ParqueDeleteView.as_view(), name='parque-delete'),

    path('<int:id>/zona/', ZonaListView.as_view(), name='zona-list'),
    path('<int:id>/zona/<int:pk>/', ZonaDetailView.as_view(), name='zona-detail'),
    path('<int:id>/zona/<int:pk>/delete/', ZonaDeleteView.as_view(), name='zona-delete'),
    path('<int:id>/zona/create/', ZonaCreateView.as_view(), name='zona-create'),
    path('<int:id>/zona/<int:pk>/update/', ZonaUpdateView.as_view(), name='zona-update'),

    path('<int:id>/zona/<int:pk>/lugar/', LugarListView.as_view(), name='lugar-list'),
    path('<int:id>/zona/<int:pk>/lugar/<int:lugar>/', LugarDetailView.as_view(), name='lugar-detail'),
    path('<int:id>/zona/<int:pk>/lugar/<int:lugar>/delete/', LugarDeleteView.as_view(), name='lugar-delete'),
    path('<int:id>/zona/<int:pk>/lugar/create/', LugarCreateView.as_view(), name='lugar-create'),
    path('<int:id>/zona/<int:pk>/lugar/<int:lugar>/update/', LugarUpdateView.as_view(), name='lugar-update'),

    path('<int:id>/zona/create/erro/', ZonaErrorView.as_view()),
    path('<int:id>/zona/<int:pk>/lugar/create/erro/', LugarErrorView.as_view()),
    path('<int:id>/zona/create/erro/erro/', ErrorView.as_view()),
    path('<int:id>/zona/<int:pk>/update/erro/', ErrorErrorView.as_view()),
]

OperationManagement/urls.py
from django.urls import path

from . import views

app_name = "OperationManagement"

urlpatterns = [
    path("", views.entrar_parque, name="entrar_parque"),
    path("entrar_parque_form/<int:parque_id>/", views.entrar_parque_form, name="entrar_parque_form"),
    path("index/<int:parque_id>/", views.index, name="index"),
    path("sair_parque_form/<int:parque_id>", views.sair_parque_form, name="sair_parque_form"),
    path("ocupar_lugar/<int:parque_id>/<int:lugar_id>/", views.ocupar_lugar, name="ocupar_lugar"),
    path("liberar_lugar/<int:parque_id>/<int:lugar_id>/", views.liberar_lugar, name="liberar_lugar"),
    path("associar_lugar/<int:parque_id>/<int:zona_id>/", views.associar_lugar, name="associar_lugar"),
    path("desassociar_lugar/<int:parque_id>/<int:zona_id>/", views.desassociar_lugar, name="desassociar_lugar"),

    # path('reclamacao/', views.ReclamacaoListView.as_view(), name='reclamacao-list'), #consultar reclamacoes
    # path("consultar_entradas/<int:parque_id>/<int:fatura_id>/", views.consultar_entradas, name="consultar_entradas"), #reclamar fatura
    path("reclamar_fatura/<int:parque_id>/<int:fatura_id>/", views.reclamar_fatura, name="reclamar_fatura"),
    path("processar_reclamacao/<int:parque_id>/<int:reclamacao_id>", views.processar_reclamacao, name="processar_reclamacao"), #cancelar fatura
    # path('fatura/<int:id>/processar/', views.ProcessFaturaView.as_view(), name="processar_reclamacao"), #processar fatura
]

PaymentManagement/urls.py
from django.urls import path, include
from . import models, views

app_name = "PaymentManagement"
urlpatterns = [
    #GESTAO DE CONTRATOS
    path('', views.OptionsView.as_view(), name='options'), #consultar contratos
    path('contrato/', views.contratos_list.as_view(), name='contrato-list'), #consultar contratos
    path('contrato/<int:id>/', views.contrato_detail_view, name="contrato-detail"), #vista detalhada de um contrato
    path('contrato/criar/', views.contrato_parque_view, name="contrato-parque"), #Escolher parque para criar contrato
    path('contrato/criar/<int:id>', views.contrato_create_view, name="contrato-create"), #dados para criar contrato
    path('contrato/<int:id>/editar/', views.contrato_update_view, name="contrato-update"), #editar o contrato
    path('contrato/<int:id>/apagar/', views.contrato_delete_view, name="contrato-delete"), #cancelar o contrato
    path('contrato/<int:id>/validar/aprovar/', views.contrato_validate_aprove_view, name="contrato-validate-aprove"), #validar o contrato (aprovar)
    path('contrato/<int:id>/validar/cancelar/', views.contrato_validate_desaprove_view, name="contrato-validate-desaprove"), #validar o contrato (cancelar)

    #GESTAO DE FATURACAO
    path('reserva/<int:id>/pagar/', views.reserva_payment_create_view, name="reserva-pay"), #efetuar pagamento reserva
    path('registo/<int:id>/pagar/', views.registo_payment_create_view, name="registo-pay"), #efetuar pagamento registo
    path('contrato/<int:id>/pagar/<int:payid>/', views.PaymentOptionsView.as_view(), name="contrato-pay-options"), #dados de pagamento para contrato
    path('contrato/<int:id>/pagar/<int:payid>/cartao', views.payment_create_view, name="contrato-pay-card"), #dados de pagamento para contrato
    path('contrato/<int:id>/pagar/<int:payid>/referencia', views.payment_create_view_reference, name="contrato-pay-reference"), #dados de pagamento para contrato
    path('fatura/', views.FaturaListView.as_view(), name="fatura"), #consultar faturas
    path('pagamento/<int:id>/emitir/', views.emit_fatura_view, name="fatura-emit"), #emitir fatura
    path('pagamento/', views.payment_view.as_view(), name="payment"), #consultar pagamentos
    path('pagamento/<int:id>/comprovar/', views.payment_prove_create_view, name="payment-prove"), #comprovar pagamento
    path('reclamacao/', views.ReclamacaoListView.as_view(), name='reclamacao-list'), #consultar reclamacoes
    path('fatura/<int:id>/reclamar/', views.ReclamacaoCreateView.as_view(), name="fatura-reclam"), #reclamar fatura
    path('fatura/<int:id>/cancelar/', views.FaturaDeleteView.as_view(), name="fatura-cancel"), #cancelar fatura
    path('fatura/<int:id>/processar/', views.ProcessFaturaView.as_view(), name="fatura-process"), #processar fatura
]

ReserveManagement/urls.py
from django.urls import path
from . import views

app_name = "ReserveManagement"

urlpatterns = [
    path('', views.homepage, name="homepage"),
    path('create/', views.create, name="create"),
    path('read/', views.read, name="read"),
    path('update/<int:reserva_id>', views.update, name='update'),
    path('delete/<int:reserva_id>', views.delete, name='delete'),
    path('create_table/', views.createTable, name="create_table"),
    path('read_table/', views.readTable, name="read_table"),
    path('delete_table/<int:tabela_id>', views.deleteTable, name='delete_table'),
    path('update_table/<int:tabela_id>', views.updateTable, name='update_table'),
]

les/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('OperationManagement/', include('OperationManagement.urls')),
    path('AdminManagement/', include('AdminManagement.urls')),
    path('PaymentManagement/', include('PaymentManagement.urls')),
    path('ReserveManagement/', include('ReserveManagement.urls')),
    path('', include('Index.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

Index/templates/content.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!-- Recent Sales Start -->
    <div class="container-fluid pt-4 px-4">
        <div class="bg-light text-center rounded p-4">
            <div class="d-flex align-items-center justify-content-between mb-4">
                <h6 class="mb-0">Recent Salse</h6>
                <a href="">Show All</a>
            </div>
            <div class="table-responsive">
                <table class="table text-start align-middle table-bordered table-hover mb-0">
                    <thead>
                        <tr class="text-dark">
                            <th scope="col"><input class="form-check-input" type="checkbox"></th>
                            <th scope="col">Date</th>
                            <th scope="col">Invoice</th>
                            <th scope="col">Customer</th>
                            <th scope="col">Amount</th>
                            <th scope="col">Status</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><input class="form-check-input" type="checkbox"></td>
                            <td>01 Jan 2045</td>
                            <td>INV-0123</td>
                            <td>Jhon Doe</td>
                            <td>$123</td>
                            <td>Paid</td>
                            <td><a class="btn btn-sm btn-primary" href="">Detail</a></td>
                        </tr>
                        <tr>
                            <td><input class="form-check-input" type="checkbox"></td>
                            <td>01 Jan 2045</td>
                            <td>INV-0123</td>
                            <td>Jhon Doe</td>
                            <td>$123</td>
                            <td>Paid</td>
                            <td><a class="btn btn-sm btn-primary" href="">Detail</a></td>
                        </tr>
                        <tr>
                            <td><input class="form-check-input" type="checkbox"></td>
                            <td>01 Jan 2045</td>
                            <td>INV-0123</td>
                            <td>Jhon Doe</td>
                            <td>$123</td>
                            <td>Paid</td>
                            <td><a class="btn btn-sm btn-primary" href="">Detail</a></td>
                        </tr>
                        <tr>
                            <td><input class="form-check-input" type="checkbox"></td>
                            <td>01 Jan 2045</td>
                            <td>INV-0123</td>
                            <td>Jhon Doe</td>
                            <td>$123</td>
                            <td>Paid</td>
                            <td><a class="btn btn-sm btn-primary" href="">Detail</a></td>
                        </tr>
                        <tr>
                            <td><input class="form-check-input" type="checkbox"></td>
                            <td>01 Jan 2045</td>
                            <td>INV-0123</td>
                            <td>Jhon Doe</td>
                            <td>$123</td>
                            <td>Paid</td>
                            <td><a class="btn btn-sm btn-primary" href="">Detail</a></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- Recent Sales End -->
</body>
</html>

Index/templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
    <!-- Footer Start -->
    <footer>
        <div class="col-12 col-sm-6 text-center text-sm-start">
            &copy; <a href="#">Your Site Name</a>, All Right Reserved. 
        </div>
        <div class="col-12 col-sm-6 text-center text-sm-end">
            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
            Designed By <a href="https://htmlcodex.com">HTML Codex</a>
        </br>
        Distributed By <a class="border-bottom" href="https://themewagon.com" target="_blank">ThemeWagon</a>
        </div>
    </footer>
    <!-- Footer End -->
</body>
</html>

Index/templates/loading.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="container-xxl position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
</body>
</html>

Index/templates/navbar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<body>
    <!-- Content Start -->
    <div class="content">
        <!-- Navbar Start -->
        <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
            <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
                <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2>
            </a>
            <a href="#" class="sidebar-toggler flex-shrink-0">
                <i class="fa fa-bars"></i>
            </a>
            <form class="d-none d-md-flex ms-4">
                <input class="form-control border-0" type="search" placeholder="Search">
            </form>
            <div class="navbar-nav align-items-center ms-auto">
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                        <i class="fa fa-envelope me-lg-2"></i>
                        <span class="d-none d-lg-inline-flex">Message</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                        <a href="#" class="dropdown-item">
                            <div class="d-flex align-items-center">
                                <img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                <div class="ms-2">
                                    <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                    <small>15 minutes ago</small>
                                </div>
                            </div>
                        </a>
                        <hr class="dropdown-divider">
                        <a href="#" class="dropdown-item">
                            <div class="d-flex align-items-center">
                                <img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                <div class="ms-2">
                                    <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                    <small>15 minutes ago</small>
                                </div>
                            </div>
                        </a>
                        <hr class="dropdown-divider">
                        <a href="#" class="dropdown-item">
                            <div class="d-flex align-items-center">
                                <img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                <div class="ms-2">
                                    <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                    <small>15 minutes ago</small>
                                </div>
                            </div>
                        </a>
                        <hr class="dropdown-divider">
                        <a href="#" class="dropdown-item text-center">See all message</a>
                    </div>
                </div>
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                        <i class="fa fa-bell me-lg-2"></i>
                        <span class="d-none d-lg-inline-flex">Notificatin</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                        <a href="#" class="dropdown-item">
                            <h6 class="fw-normal mb-0">Profile updated</h6>
                            <small>15 minutes ago</small>
                        </a>
                        <hr class="dropdown-divider">
                        <a href="#" class="dropdown-item">
                            <h6 class="fw-normal mb-0">New user added</h6>
                            <small>15 minutes ago</small>
                        </a>
                        <hr class="dropdown-divider">
                        <a href="#" class="dropdown-item">
                            <h6 class="fw-normal mb-0">Password changed</h6>
                            <small>15 minutes ago</small>
                        </a>
                        <hr class="dropdown-divider">
                        <a href="#" class="dropdown-item text-center">See all notifications</a>
                    </div>
                </div>
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                        <img class="rounded-circle me-lg-2" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
                        <span class="d-none d-lg-inline-flex">John Doe</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                        <a href="#" class="dropdown-item">My Profile</a>
                        <a href="#" class="dropdown-item">Settings</a>
                        <a href="#" class="dropdown-item">Log Out</a>
                    </div>
                </div>
            </div>
        </nav>
        <!-- Navbar End -->
        
        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-light navbar-light">
                <a href="index.html" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary">PARQUE</h3>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">Jhon Doe</h6>
                        <span>Admin</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a href="index.html" class="nav-item nav-link active"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-laptop me-2"></i>Elements</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="button.html" class="dropdown-item">Buttons</a>
                            <a href="typography.html" class="dropdown-item">Typography</a>
                            <a href="element.html" class="dropdown-item">Other Elements</a>
                        </div>
                    </div>
                    <a href="{% url 'OperationManagement:entrar_parque' %}" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Operation</a>
                    <a href="{% url 'AdminManagement:parque-list' %}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Admin</a>
                    <a href="{% url 'PaymentManagement:options' %}" class="nav-item nav-link"><i class="fa fa-table me-2"></i>Payment</a>
                    <a href="{% url 'ReserveManagement:homepage' %}" class="nav-item nav-link"><i class="fa fa-chart-bar me-2"></i>Reserva</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="far fa-file-alt me-2"></i>Pages</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="signin.html" class="dropdown-item">Sign In</a>
                            <a href="signup.html" class="dropdown-item">Sign Up</a>
                            <a href="404.html" class="dropdown-item">404 Error</a>
                            <a href="blank.html" class="dropdown-item">Blank Page</a>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->
</body>
</html>

Index/templates/welcome_screen.html
{% load static %}
<!doctype html>
<html>
<head>
    <head>
        <meta charset="utf-8">
        <title>Parque do CRL</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">
    
        <!-- Favicon -->
        <link href="{% static 'img/favicon.ico' %}" rel="icon">
    
        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
        
        <!-- Icon Font Stylesheet -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    
        <!-- Libraries Stylesheet -->
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />
    
        <!-- Customized Bootstrap Stylesheet -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    
        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>
<body>
    <!--<h1>This is a navbar</h1>-->
    {% include 'loading.html' %}
    {% include 'navbar.html' %}
    {% include 'content.html' %}
    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/chart/chart.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>