OperationManagement/urls.py
from django.urls import path

from . import views

app_name = "OperationManagement"

urlpatterns = [
    path("", views.entrar_parque, name="entrar_parque"),
    path("entrar_parque_form/<int:parque_id>/", views.entrar_parque_form, name="entrar_parque_form"),
    path("index/<int:parque_id>/", views.index, name="index"),
    path("sair_parque_form/<int:parque_id>", views.sair_parque_form, name="sair_parque_form"),
    path("ocupar_lugar/<int:parque_id>/<int:lugar_id>/", views.ocupar_lugar, name="ocupar_lugar"),
    path("liberar_lugar/<int:parque_id>/<int:lugar_id>/", views.liberar_lugar, name="liberar_lugar"),
    path("associar_lugar/<int:parque_id>/<int:zona_id>/", views.associar_lugar, name="associar_lugar"),
    path("desassociar_lugar/<int:parque_id>/<int:zona_id>/", views.desassociar_lugar, name="desassociar_lugar"),

    # path('reclamacao/', views.ReclamacaoListView.as_view(), name='reclamacao-list'), #consultar reclamacoes
    # path("consultar_entradas/<int:parque_id>/<int:fatura_id>/", views.consultar_entradas, name="consultar_entradas"), #reclamar fatura
    path("reclamar_fatura/<int:parque_id>/<int:fatura_id>/", views.reclamar_fatura, name="reclamar_fatura"),
    path("processar_reclamacao/<int:parque_id>/<int:reclamacao_id>", views.processar_reclamacao, name="processar_reclamacao"), #cancelar fatura
    # path('fatura/<int:id>/processar/', views.ProcessFaturaView.as_view(), name="processar_reclamacao"), #processar fatura
]

les/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('OperationManagement/', include('OperationManagement.urls')),
    path('AdminManagement/', include('AdminManagement.urls')),
    path('PaymentManagement/', include('PaymentManagement.urls')),
    path('ReserveManagement/', include('ReserveManagement.urls')),
    path('', include('Index.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

OperationManagement/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from datetime import datetime
from django.db import models



class RegistoMovimento(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    parqueid = models.ForeignKey('AdminManagement.Parque', models.CASCADE, db_column='ParqueID', default=1)  # Field name made lowercase.
    matricula = models.CharField(db_column='Matricula', max_length=255, blank=True, null=True)  # Field name made lowercase.
    data_de_entrada = models.DateTimeField(default=datetime.now, db_column='Data de entrada', blank=False, null=False)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    data_de_saida = models.DateTimeField(auto_now=False, auto_now_add=False, db_column='Data de saida', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    provas = models.CharField(db_column='Provas', max_length=255, blank=True, null=True)  # Field name made lowercase.

    def __str__(self):
        saida = ""
        if (self.data_de_saida != None):
            saida = self.data_de_saida
        return 'AdminManagementParque'.__str__(self.parqueid) + ", Matrícula: " + str(self.matricula) + ", Entrada: " + str(self.data_de_entrada) + ", Saída: " + str(self.data_de_saida)

    class Meta:
        db_table = 'RegistoMovimento'

class Viatura(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    contratoid = models.ForeignKey('PaymentManagement.Contrato', models.CASCADE, db_column='ContratoID', null=True)  # Field name made lowercase.
    registo_movimentoid = models.ForeignKey(RegistoMovimento, models.CASCADE, db_column='Registo-movimentoID')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    marca = models.CharField(db_column='Marca', max_length=255, blank=True, null=True)  # Field name made lowercase.
    modelo = models.CharField(db_column='Modelo', max_length=255, blank=True, null=True)  # Field name made lowercase.
    matricula = models.CharField(db_column='Matricula', max_length=255, blank=True, null=True)  # Field name made lowercase.

    def __str__(self):
        return str(self.matricula)

    class Meta:
        db_table = 'Viatura'


class TabelaMatriculas(models.Model):
    pais = models.CharField(db_column='Pais', max_length=255)
    formato = models.CharField(db_column='Formato', max_length=255)

    def __str__(self):
        return "País: " + str(self.pais) + ", Formato: " + str(self.formato)

    class Meta:
        db_table = 'TabelaMatriculas'

OperationManagement/views.py
import random

from django.contrib import messages
from django.utils import timezone
from django.shortcuts import render, redirect
from django.views import View

from AdminManagement.models import Lugar, Parque, Zona
from PaymentManagement.models import Fatura, Reclamacao
from .forms import AssociarLugarForm, DesassociarLugarForm, EntrarParqueForm, ReclamacaoForm, RegistoMovimentoModelForm, SairParqueForm

from .models import RegistoMovimento, Viatura


# Create your views here.

def entrar_parque(request):
    return render(request=request,
                  template_name="main/entrar_parque.html",
                  context={"parques": Parque.objects.all()})


def entrar_parque_form(request, parque_id):
    parques = Parque.objects.get(pk=parque_id)
    if request.method == "POST":
        form = EntrarParqueForm(request.POST)
        if form.is_valid():
            messages.success(request, f"Entrou no parque com sucesso.")
            r = RegistoMovimento(data_de_entrada=timezone.now(), matricula=form.cleaned_data.get("matricula"), parqueid=parques)
            r.save()
            v = Viatura(registo_movimentoid=r, matricula=form.cleaned_data.get("matricula"))
            v.save()

            return redirect("OperationManagement:index", parque_id=parque_id)
    else:
        form = EntrarParqueForm

    return render(request,
                  "main/entrar_parque_form.html",
                  context={"form": form, "parques": parques})


def index(request, parque_id):
    parque= Parque.objects.get(pk=parque_id)
    zonas = Zona.objects.filter(parqueid=parque)
    lugares = Lugar.objects.all()
    faturas = Fatura.objects.all()
    reclamacoes = Reclamacao.objects.all()

    return render(request=request,
                  template_name="main/index.html",
                  context={"parque": parque, "zonas": zonas, "lugares": lugares, "faturas": faturas, "reclamacoes": reclamacoes})


# Ver isto melhor
def sair_parque_form(request, parque_id):
    parques = Parque.objects.get(pk=parque_id)
    if request.method == "POST":
        form = SairParqueForm(request.POST)
        if form.is_valid():
            v = Viatura.objects.filter(matricula=form.cleaned_data.get("matricula"))

            messages.success(request, f"Saiu do parque com sucesso.")
            return redirect("OperationManagement:entrar_parque")

    else:
        form = SairParqueForm

    return render(request,
                  "main/sair_parque_form.html",
                  context={"form": form, "parques": parques})


def ocupar_lugar(request, parque_id, lugar_id):
    parque = Parque.objects.get(pk=parque_id)
    zonas = Zona.objects.filter(parqueid=parque)
    lugares = Lugar.objects.none()
    for zona in zonas:
        lugares |= Lugar.objects.filter(zonaid=zona)

    lugares_livres = lugares.filter(estado="Livre")
    if not lugares_livres:
        messages.error(request, f"Não existem lugares livres no parque.")
        return redirect("OperationManagement:index", parque_id=parque_id)

    lugar = Lugar.objects.get(numero_do_lugar=lugar_id)
    lugar.estado = "Ocupado"
    lugar.save()

    messages.success(request, f"Ocupou o lugar no parque.")

    return redirect("OperationManagement:index", parque_id=parque_id)


def liberar_lugar(request, parque_id, lugar_id):
    parque = Parque.objects.get(pk=parque_id)
    zonas = Zona.objects.filter(parqueid=parque)
    lugares = Lugar.objects.none()
    for zona in zonas:
        lugares |= Lugar.objects.filter(zonaid=zona)

    lugares_ocupados = lugares.filter(estado="Ocupado")
    if not lugares_ocupados:
        messages.error(request, f"Não existem lugares ocupados no parque.")
        return redirect("OperationManagement:index", parque_id=parque_id)

    lugar = Lugar.objects.get(numero_do_lugar=lugar_id)
    lugar.estado = "Livre"
    lugar.save()

    messages.success(request, f"Liberou o lugar no parque.")

    return redirect("OperationManagement:index", parque_id=parque_id)


def associar_lugar(request, parque_id, zona_id):
    parques = Parque.objects.get(pk=parque_id)
    zona = Zona.objects.get(numero_da_zona=zona_id)
    if request.method == "POST":
        form = AssociarLugarForm(zona, request.POST)
        if form.is_valid():

            messages.success(request, f"Associou o lugar com sucesso.")
            l = form.cleaned_data.get("lugar")
            m = form.cleaned_data.get("matricula")
            v = Viatura.objects.get(matricula=m)
            l.viaturaid = v
            l.save()

            return redirect("OperationManagement:index", parque_id=parque_id)
    else:
        form = AssociarLugarForm(zona)

    return render(request,
                  "main/associar_lugar.html",
                  context={"form": form, "parques": parques})


def desassociar_lugar(request, parque_id, zona_id):
    parques = Parque.objects.get(pk=parque_id)
    zona = Zona.objects.get(numero_da_zona=zona_id)
    if request.method == "POST":
        form = DesassociarLugarForm(zona, request.POST)
        if form.is_valid():
            messages.success(request, f"Desassociou o lugar com sucesso.")

            l = form.cleaned_data.get("lugar")
            l.viaturaid = None
            l.save()

            return redirect("OperationManagement:index", parque_id=parque_id)
    else:
        form = DesassociarLugarForm(zona)

    return render(request,
                  "main/desassociar_lugar.html",
                  context={"form": form, "parques": parques})


def consultar_entradas(request, parque_id, fatura_id):
    parques = Parque.objects.get(pk=parque_id)
    fatura = Fatura.objects.get(id=fatura_id)
    p = fatura.pagamentoid
    v = p.viaturaid
    registos = RegistoMovimento.objects.filter(matricula=v.matricula)

    return render(request=request,
                  template_name="main/consultar_entradas.html",
                  context={"parques": parques, "fatura": fatura, "registos": registos})

def consultar_reclamacoes(request, parque_id, fatura_id):
    parques = Parque.objects.get(pk=parque_id)
    fatura = Fatura.objects.get(id=fatura_id)
    p = fatura.pagamentoid
    v = p.viaturaid
    registos = RegistoMovimento.objects.filter(matricula=v.matricula)

    return render(request=request,
                  template_name="main/consultar_entradas.html",
                  context={"parques": parques, "fatura": fatura, "registos": registos})

class ReclamacaoListView(View):
    template_name = 'reclamacao_list.html'
    queryset = Reclamacao.objects.all()

    def get(self, request, *args, **kwargs):
        context = {"object_list": self.queryset}
        return render(request, self.template_name, context)


def reclamar_fatura(request, parque_id, fatura_id):
    parques = Parque.objects.get(pk=parque_id)
    fatura = Fatura.objects.get(id=fatura_id)

    if request.method == "POST":
        form = ReclamacaoForm(fatura, request.POST)
        if form.is_valid():
            messages.success(request, f"Fez a reclamação com sucesso.")

            rec = Reclamacao(faturaid=fatura)
            rec.reclamacao = form.cleaned_data.get("reclamacao")
            rec.registo_movimentoid = form.cleaned_data.get("registo")
            rec.save()

            return redirect("OperationManagement:index", parque_id=parque_id)
    else:
        form = ReclamacaoForm(fatura)

    return render(request=request,
                  template_name="main/reclamar_fatura.html",
                  context={"form": form, "parques": parques, "fatura": fatura})


def processar_reclamacao(request, parque_id, reclamacao_id):
    parques = Parque.objects.get(pk=parque_id)
    reclamacao = Reclamacao.objects.get(id=reclamacao_id)
    registo = reclamacao.registo_movimentoid
    v = Viatura.objects.get(matricula=registo.matricula)
    fatura = reclamacao.faturaid

    if request.method == 'POST':
        form = RegistoMovimentoModelForm(registo, request.POST)
        if form.is_valid():

                # fatura.delete()
                registo.matricula = form.cleaned_data.get("matricula")
                v.matricula = form.cleaned_data.get("matricula")
                registo.data_de_entrada = form.cleaned_data.get("data_de_entrada")
                registo.data_de_saida = form.cleaned_data.get("data_de_saida")
                registo.provas = form.cleaned_data.get("provas")
                registo.save()

                # Criar nova fatura com dados novos de movimento

                return redirect('OperationManagement:index', parque_id=parque_id)
    else:
        form = RegistoMovimentoModelForm(registo)

    return render(request=request,
              template_name="main/processar_reclamacao.html",
              context={"parques": parques, "form": form, "reclamacao": reclamacao})

OperationManagement/templates/main/associar_lugar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Associar Lugar</title>

    {% load static %}
    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">

</head>
<body>

{% include "main/includes/messages.html" %}

        <div class="container">
            <form method="POST">
                {% csrf_token %}

                <div class="container">
                    <h3 style="padding: 2em">Associando um lugar em {{ parques.nome }}</h3>
                </div>

                <div class="container" style="padding: 0.5em">
                     {{ form.as_p }}
                 </div>

                <div class="container-fluid" style="padding: 2em">
                    <a class="btn btn-danger" href="{% url 'OperationManagement:index' parque_id=parques.id %}" style="color: white; margin-right: 1em" type="submit">Voltar</a>
                    <button class="btn btn-primary" href="{% url 'OperationManagement:index' parque_id=parques.id %}" type="submit">Associar</button>
                </div>
                </form>
        </div>

</body>
</html>

OperationManagement/templates/main/consultar_entradas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Consultar registo de entradas</title>

    {% load static %}
    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">

</head>
<body>

        <a class="btn btn-danger" href="{% url 'OperationManagement:index' parque_id=parques.id %}" style="color: white; margin-right: 1em" type="submit">Voltar</a>

        <div class="container">
            {% for registo in registos %}
                {{ registo.data_de_entrada }}  <a class="btn btn-primary" href="{% url 'OperationManagement:reclamar_fatura' parque_id=parques.id fatura_id=fatura.id %}" style="color: white; margin-right: 1em" type="submit">Fazer reclamação</a>
            {% endfor %}
        </div>

</body>
</html>

OperationManagement/templates/main/consultar_reclamacoes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Consultar registos de reclamações</title>
</head>
<body>

    <a class="btn btn-danger" href="{% url 'OperationManagement:index' parque_id=parques.id %}" style="color: white; margin-right: 1em" type="submit">Voltar</a>

    <div class="container">
        {% for registo in registos %}
            {{ registo.data_de_entrada }}  <a class="btn btn-primary" href="{% url 'OperationManagement:reclamar_fatura' parque_id=parques.id fatura_id=fatura.id %}" style="color: white; margin-right: 1em" type="submit">Fazer reclamação</a>
        {% endfor %}
    </div>

</body>
</html>

OperationManagement/templates/main/desassociar_lugar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Desassociar Lugar</title>

    {% load static %}
    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">

</head>
<body>

{% include "main/includes/messages.html" %}

        <div class="container">
            <form method="POST">
                {% csrf_token %}

                <div class="container">
                    <h3 style="padding: 2em">Desassociando um lugar em {{ parques.nome }}</h3>
                </div>

                <div class="container" style="padding: 0.5em">
                     {{ form.as_p }}
                 </div>

                <div class="container-fluid" style="padding: 2em">
                    <a class="btn btn-danger" href="{% url 'OperationManagement:index' parque_id=parques.id %}" style="color: white; margin-right: 1em" type="submit">Voltar</a>
                    <button class="btn btn-primary" href="{% url 'OperationManagement:index' parque_id=parques.id %}" type="submit">Desassociar</button>
                </div>
                </form>
        </div>

</body>
</html>

OperationManagement/templates/main/entrar_parque.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Selecionar parque</title>

    {% load static %}
    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/bootstrap.bundle.min.js' %}" rel="stylesheet">

</head>
<body>

  {% include "main/includes/messages.html" %}

    <h2 class="text-center" style="padding: 1em">Escolha o parque em que pretende entrar:</h2>

        <div class="container-fluid">
            <div class="row">
                {% for parque in parques %}
                <div class="col-md-3 text-center">
                        <img class="h-75 border border-dark rounded p-4" height="150px" width="300px" src="static/main/img/{{ parque.foto }}">
                        <h2><a href="{% url 'OperationManagement:entrar_parque_form' parque_id=parque.id %}">{{ parque.nome }}</a></h2>
                </div>
                 {% endfor %}
            </div>
        </div>

</body>
</html>

OperationManagement/templates/main/entrar_parque_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">
    <title>{{ parques.nome }} - Entrar</title>
</head>
<body>

{% include "main/includes/messages.html" %}

 <div class="container">

        <div class="container">
            <h3 style="text-align: center; padding: 1em">Bem-vindo a {{ parques.nome }}!</h3>
        </div>

         <div class="container-fluid" style="padding: 0.5em">
             <div class="row">

                 <div class="col-md-4">
                     </div>
                 <div class="col-md-4 text-center" style="padding: 2em">
                     <form method="POST">
                        {% csrf_token %}

                         {{ form }}
                         <br>
                         <a class="btn btn-danger" style="color: white; margin-right: 2em; margin-top: 2em" href="/">Voltar</a>
                         <button class="btn btn-primary" style="margin-top: 2em" type="submit">Entrar</button>
                     </form>

                 <div>
                 <div class="col-md-4">
                 </div>

             </div>
         </div>

</div>

</body>
</html>

OperationManagement/templates/main/fazer_reclamacao.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fazer reclamação</title>

    {% load static %}
    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">

</head>
<body>

        <div class="container">
            <form method="POST">
                {% csrf_token %}

                <div class="container">
                    <h3 style="padding: 2em">Fazer reclamação</h3>
                </div>

                <div class="container" style="padding: 0.5em">
                     {{ form.as_p }}
                 </div>

                <div class="container-fluid" style="padding: 2em">
                    <a class="btn btn-danger" href="{% url 'OperationManagement:index' parque_id=parques.id %}" style="color: white; margin-right: 1em" type="submit">Voltar</a>
                    <button class="btn btn-primary" href="{% url 'OperationManagement:index' parque_id=parques.id %}" type="submit">Enviar reclamação</button>
                </div>
                </form>
        </div>

</body>
</html>

OperationManagement/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">


    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>


        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">

                       <a href="{% url 'OperationManagement:sair_parque_form' parque_id=parque.id %}">
                           <button style="margin-top: 1em" class="btn btn-danger">Sair de {{ parque.nome }}</button>
                       </a>

                    <h3 style="text-align: center">{{ parque.nome }}</h3>

                </div>
            </div>
        </div>

        {% include "main/includes/messages.html" %}

        <div class="container">
            <div class="row">
                <h2 style="padding: 2em">Lista de zonas</h2>
                    {% for zona in zonas %}
                    <div class="col-md-3" style="padding: 1em">
                                <div class="h-100 border border-dark rounded p-4">
                                    {{ zona.numero_da_zona }}
                                    <br>
                                    Lugares:  {{ zona.lugares }}
                                    <br>
                                    <div class="container-fluid text-center">
                                        <a class="btn btn-success" style="color: white;margin-bottom: 1em; margin-top: 1em" href="{% url 'OperationManagement:associar_lugar' parque_id=parque.id zona_id=zona.numero_da_zona %}">
                                            Associar lugar
                                        </a>
                                        <a class="btn btn-danger" href="{% url 'OperationManagement:desassociar_lugar' parque_id=parque.id zona_id=zona.numero_da_zona %}">
                                            Desassociar lugar
                                        </a>
                                    </div>
                                </div>
                            </div>
                    {% endfor %}
                <br>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <h2 style="padding: 2em">Lista de lugares</h2>

                    {% for lugar in lugares %}
                    <br>
                        {% if lugar.estado == "Ocupado"%}
                            <div class="col-md-2" style="padding: 1em">
                                <div class="h-100 border border-dark rounded p-4">
                                    {{ lugar.numero_do_lugar }}
                                    <p style="color: red">Ocupado</p>
                                    <a href="{% url 'OperationManagement:liberar_lugar' parque_id=parque.id lugar_id=lugar.numero_do_lugar %}">
                                        Liberar lugar
                                    </a>
                                    <br>
                                </div>
                            </div>

                        {% endif%}

                        {% if lugar.estado == "Livre"%}
                        <div class="col-md-2" style="padding: 1em">
                            <div class="h-100 border border-dark rounded p-4">
                                {{ lugar.numero_do_lugar }}
                                <p style="color: green">Livre</p>
                                <a href="{% url 'OperationManagement:ocupar_lugar' parque_id=parque.id lugar_id=lugar.numero_do_lugar %}">
                                    Ocupar lugar
                                </a>
                            </div>
                        </div>
                        {% endif %}

                    {% endfor %}
            </div>
            <br>
        </div>

        {% for fatura in faturas %}
        <a class="btn btn-primary" style="margin-top: 1em; margin-left: 1em; color: white" href="{% url 'OperationManagement:reclamar_fatura' parque_id=parque.id fatura_id=fatura.id %}">
            Reclamar de {{ fatura.nomeEmpresa }}
        </a>
        {% endfor %}

        {% for reclamacao in reclamacoes %}
         <a class="btn btn-primary" style="margin-top: 1em; margin-left: 1em; color: white" href="{% url 'OperationManagement:processar_reclamacao' parque_id=parque.id fatura_id=fatura.id %}">
                Processar reclamação de {{ reclamacao.faturaid }}
         </a>
        {% endfor %}

</body>
</html>

OperationManagement/templates/main/processar_reclamacao.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Processar reclamação</title>

    {% load static %}
    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">

</head>
<body>

        <div class="container">
            <h3 style="text-align: center; padding: 1em">Processar reclamação {{ reclamacao.id }}</h3>
        </div>

         <div class="container-fluid" style="padding: 0.5em">
             <div class="row">

                 <div class="col-md-4">
                     </div>
                 <div class="col-md-4 text-center" style="padding: 2em">
                     <form method="POST">
                        {% csrf_token %}

                         {{ form.as_p }}
                         <br>
                         <a class="btn btn-danger" style="color: white; margin-right: 2em; margin-top: 2em" href="{% url 'operation:index' parques.id %}">Voltar</a>
                         <button class="btn btn-primary" style="margin-top: 2em" type="submit">Processar</button>
                     </form>

                 <div>
                 <div class="col-md-4">
                 </div>

             </div>
         </div>

</body>
</html>

OperationManagement/templates/main/reclamar_fatura.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fazer reclamação</title>

    {% load static %}
    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">

</head>
<body>

        <div class="container">
            <form method="POST">
                {% csrf_token %}

                <div class="container">
                    <h3 style="padding: 2em">Fazer reclamação</h3>
                </div>

                <div class="container" style="padding: 0.5em">
                     {{ form.as_p }}
                 </div>

                <div class="container-fluid" style="padding: 2em">
                    <a class="btn btn-danger" href="{% url 'OperationManagement:index' parque_id=parques.id %}" style="color: white; margin-right: 1em" type="submit">Voltar</a>
                    <button class="btn btn-primary" href="{% url 'OperationManagement:index' parque_id=parques.id %}" type="submit">Enviar reclamação</button>
                </div>
                </form>
        </div>

</body>
</html>

OperationManagement/templates/main/sair_parque_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ parques.nome }} - Sair</title>

    {% load static %}
    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">

</head>
<body>

<div class="container">
    <h3 style="text-align: center; padding: 1em">Saindo de {{ parques.nome }}...</h3>
</div>

    {% include "main/includes/messages.html" %}

    <div class="container-fluid" style="padding: 0.5em">
             <div class="row">

                 <div class="col-md-4">
                     </div>
                 <div class="col-md-4 text-center" style="padding: 2em">
                     <form method="POST">
                        {% csrf_token %}

                         {{ form }}
                         <br>
                         <a class="btn btn-danger" style="color: white; margin-right: 2em; margin-top: 2em" href="{% url 'OperationManagement:index' parque_id=parques.id %}">Voltar</a>
                         <button class="btn btn-primary" style="margin-top: 2em" type="submit">Sair</button>
                     </form>

                 <div>
                 <div class="col-md-4">
                 </div>

             </div>
         </div>

</body>
</html>