PaymentManagement/urls.py
from django.urls import path, include
from . import models, views

app_name = "PaymentManagement"
urlpatterns = [
    #GESTAO DE CONTRATOS
    path('', views.OptionsView.as_view(), name='options'), #consultar contratos
    path('contrato/', views.contratos_list.as_view(), name='contrato-list'), #consultar contratos
    path('contrato/<int:id>/', views.contrato_detail_view, name="contrato-detail"), #vista detalhada de um contrato
    path('contrato/criar/', views.contrato_parque_view, name="contrato-parque"), #Escolher parque para criar contrato
    path('contrato/criar/<int:id>', views.contrato_create_view, name="contrato-create"), #dados para criar contrato
    path('contrato/<int:id>/editar/', views.contrato_update_view, name="contrato-update"), #editar o contrato
    path('contrato/<int:id>/apagar/', views.contrato_delete_view, name="contrato-delete"), #cancelar o contrato
    path('contrato/<int:id>/validar/aprovar/', views.contrato_validate_aprove_view, name="contrato-validate-aprove"), #validar o contrato (aprovar)
    path('contrato/<int:id>/validar/cancelar/', views.contrato_validate_desaprove_view, name="contrato-validate-desaprove"), #validar o contrato (cancelar)

    #GESTAO DE FATURACAO
    path('reserva/<int:id>/pagar/', views.reserva_payment_create_view, name="reserva-pay"), #efetuar pagamento reserva
    path('registo/<int:id>/pagar/', views.registo_payment_create_view, name="registo-pay"), #efetuar pagamento registo
    path('contrato/<int:id>/pagar/<int:payid>/', views.PaymentOptionsView.as_view(), name="contrato-pay-options"), #dados de pagamento para contrato
    path('contrato/<int:id>/pagar/<int:payid>/cartao', views.payment_create_view, name="contrato-pay-card"), #dados de pagamento para contrato
    path('contrato/<int:id>/pagar/<int:payid>/referencia', views.payment_create_view_reference, name="contrato-pay-reference"), #dados de pagamento para contrato
    path('fatura/', views.FaturaListView.as_view(), name="fatura"), #consultar faturas
    path('pagamento/<int:id>/emitir/', views.emit_fatura_view, name="fatura-emit"), #emitir fatura
    path('pagamento/', views.payment_view.as_view(), name="payment"), #consultar pagamentos
    path('pagamento/<int:id>/comprovar/', views.payment_prove_create_view, name="payment-prove"), #comprovar pagamento
    path('reclamacao/', views.ReclamacaoListView.as_view(), name='reclamacao-list'), #consultar reclamacoes
    path('fatura/<int:id>/reclamar/', views.ReclamacaoCreateView.as_view(), name="fatura-reclam"), #reclamar fatura
    path('fatura/<int:id>/cancelar/', views.FaturaDeleteView.as_view(), name="fatura-cancel"), #cancelar fatura
    path('fatura/<int:id>/processar/', views.ProcessFaturaView.as_view(), name="fatura-process"), #processar fatura
]

les/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('OperationManagement/', include('OperationManagement.urls')),
    path('AdminManagement/', include('AdminManagement.urls')),
    path('PaymentManagement/', include('PaymentManagement.urls')),
    path('ReserveManagement/', include('ReserveManagement.urls')),
    path('', include('Index.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

PaymentManagement/views.py
import datetime
import random
import string
from django.urls import reverse
import stripe
from django.core.mail import send_mail
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django_tables2 import SingleTableMixin
from django.views.generic import ListView
from django.core.files.storage import FileSystemStorage

from AdminManagement.models import Lugar, Parque
from OperationManagement.models import RegistoMovimento
from .models import Reserva, TabelaPrecos

from .models import Cliente, Contrato, Dia, Fatura, Pagamento, Reclamacao
from .forms import ContratoForm, FaturaModelForm, PaymentModelForm, ReclamacaoModelForm
from django.views.generic import (
    ListView, 
    DetailView,
    CreateView,
    UpdateView,
    DeleteView, 
    TemplateView, 
    View
    )

from .tables import ContratosTable
from django_filters.views import FilterView
from .filters import ContratosFilter
from django.db.models import F
from django.template import loader

#LISTAR OS CONTRATOS
class contratos_list(SingleTableMixin, FilterView):
    table_class = ContratosTable
    template_name = 'contratos.html'
    filterset_class = ContratosFilter
    table_pagination = {
        'per_page': 10
    }

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(SingleTableMixin, self).get_context_data(**kwargs)
        table = self.get_table(**self.get_table_kwargs())
        context[self.get_context_table_name(table)] = table
        return context
    
#CONSULTAR CONTRATO
def contrato_detail_view(request, id):
    contrato=Contrato.objects.get(id=id)
    lugar=Lugar.objects.get(contratoid=contrato)
    dias=Dia.objects.filter(periodicidadeid=contrato.periodicidadeid)
    template = loader.get_template('detail.html')
    context ={
        'contrato': contrato,
        'lugar':lugar,
        'dias':dias,
    }
    return HttpResponse(template.render(context, request))

#APAGAR CONTRATO
def contrato_delete_view(request, id):
    contrato=Contrato.objects.get(id=id)
    lugar = Lugar.objects.get(contratoid=contrato)
    if request.POST:
        contrato.delete()
        oldLugar = lugar
        oldLugar.contratoid=None
        oldLugar.save()
        return redirect('../../')
    template = loader.get_template('delete_confirmation.html')
    context ={
        "contrato": contrato,
    }
    return HttpResponse(template.render(context, request))

#LISTAR PARQUES
def contrato_parque_view(request):
    parques = Parque.objects.all()
    template = loader.get_template('parque.html')
    context ={
        'parques': parques,
    }
    return HttpResponse(template.render(context, request))

#CRIAR CONTRATO
def contrato_create_view(request, id):
    if request.method=='POST':
        form = ContratoForm(request.POST, current_user=Cliente.objects.get(id=1), parque=Parque.objects.get(id=id))
        if form.is_valid():
            form.save()
            contrato = Contrato.objects.latest("id")
            pagamento = Pagamento.objects.get(contratoid=contrato.id)
            return redirect(reverse('PaymentManagement:contrato-pay-options', kwargs={ 'id': contrato.id, 'payid': pagamento.id}))
    else:
        form = ContratoForm(current_user=Cliente.objects.get(id=1))
    context ={
        'form': form,
    }
    return render(request, "create.html", context)

#EDITAR CONTRATO
def contrato_update_view(request, id):
    obj=get_object_or_404(Contrato, id=id)
    form = ContratoForm(request.POST or None, current_user=Cliente.objects.get(id=1), instance=obj)
    if form.is_valid():
        form.save(id)
        contrato = Contrato.objects.latest("id")
        return redirect(reverse('PaymentManagement:contrato-pay', kwargs={ 'id': contrato.id }))
    context ={
        'form': form,
    }
    return render(request, "create.html", context)


#APROVAR CONTRATO
def contrato_validate_aprove_view(request, id):
    contrato=Contrato.objects.get(id=id)
    contrato.valido = True
    contrato.save()
    return redirect('../../..')

#DESAPROVAR CONTRATO
def contrato_validate_desaprove_view(request, id):
    contrato=Contrato.objects.get(id=id)
    contrato.valido = False
    contrato.save()
    return redirect('../../..')


#CONSULTAR PAGAMENTOS
class payment_view(ListView):
    template_name = 'pagamentos.html'
    queryset = Pagamento.objects.all()
    faturas = Fatura.objects.values_list("pagamentoid", flat=True)

    def get(self, request, *args, **kwargs):
        context = {"object_list": self.queryset, "faturas": self.faturas}
        return render(request, self.template_name, context)

#PAGAMENTO EFETUADO COM SUCESSO
class SuccessView(TemplateView):
    template_name = "success.html"


#PAGAMENTO CANCELADO
class CancelView(TemplateView):
    template_name = "cancel.html"

class FaturaListView(View):
    template_name = 'fatura_list.html'
    queryset = Fatura.objects.all()

    def get(self, request, *args, **kwargs):
        context = {"object_list": self.queryset}
        return render(request, self.template_name, context)

class FaturaDeleteView(DeleteView):
    template_name = 'fatura_delete.html'

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Fatura, id=id_)

    def get_success_url(self):
        return '../../'

class ReclamacaoListView(View):
    template_name = 'reclamacao_list.html'
    queryset = Reclamacao.objects.all()

    def get(self, request, *args, **kwargs):
        context = {"object_list": self.queryset}
        return render(request, self.template_name, context)

class ReclamacaoCreateView(CreateView):
    template_name = 'reclamacao_create.html'
    form_class = ReclamacaoModelForm
    model = Reclamacao

    def form_valid(self, form):
        reclamacao = form.save(commit=False)
        reclamacao.faturaid = Fatura.objects.get(id=self.kwargs["id"])
        reclamacao.save()
        return redirect("../../")

    def get_success_url(self):
        return '../'

def payment_prove_create_view(request, id):
    if request.method == "POST":
        pagamento = Pagamento.objects.get(id=id)
        # if the post request has a file under the input name 'document', then save the file.
        request_file = request.FILES['document'] if 'document' in request.FILES else None
        if request_file:
                # save attached file
    
                # create a new instance of FileSystemStorage
                fs = FileSystemStorage()
                file = fs.save(request_file.name, request_file)
                # the fileurl variable now contains the url to the file. This can be used to serve the file when needed.
                fileurl = fs.url(file)
                pagamento.comprovativo = request_file
                pagamento.save()
    
    return render(request, "payment_prove.html")

def payment_create_view(request, id, payid):
    if request.method=='POST':
        form = PaymentModelForm(request.POST)
        contrato = Contrato.objects.get(id = id)
        payment = Pagamento.objects.get(id = payid)
        if form.is_valid():
            payment.estado_do_pagamento = "Pago"
            payment.save()
            return redirect('../')
    else:
        form = PaymentModelForm()
        contrato = Contrato.objects.get(id = id)

    price = TabelaPrecos.getPrice(contrato = contrato, all=False)
    context ={
        'form': form,
        'price': price,
    }
    return render(request, "payment.html", context)

def payment_create_view_reference(request, id, payid):
    S = 9  # number of characters in the string.  
    # call random.choices() string module to find the string in Uppercase + numeric data.  
    randomNum = ''.join(random.choices(string.digits, k = S))    
    reference = ' '.join([randomNum[i:i+3] for i in range(0, len(randomNum), 3)])
    entidade = 11111
    pagamento=Pagamento.objects.get(id = payid)
    template = loader.get_template('reference.html')
    context ={
        'referencia': reference,
        'entidade':entidade,
        'montante':pagamento.montante,
    }
    return HttpResponse(template.render(context, request))

def reserva_payment_create_view(request, id):
    reserva = Reserva.objects.get(id = id)
    price = TabelaPrecos.getPrice(reserva = reserva, date=reserva.data_de_inicio, all=False)
    if request.method=='POST':
        form = PaymentModelForm(request.POST)   
        if form.is_valid():
            payment = Pagamento()
            payment.data_de_vencimento = datetime.datetime.now()
            payment.estado_do_pagamento = "Pago"
            payment.montante = price
            payment.reservaid = reserva
            payment.save()
            return redirect('../../../')
    else:
        form = PaymentModelForm()

    
    context ={
        'form': form,
        'price': price,
    }
    return render(request, "payment.html", context)

def registo_payment_create_view(request, id):
    registo = RegistoMovimento.objects.get(id = id)
    price = TabelaPrecos.getPrice(registo = registo, all=False)
    if request.method=='POST':
        form = PaymentModelForm(request.POST)
        if form.is_valid():
            payment = Pagamento()
            payment.data_de_vencimento = datetime.datetime.now()
            payment.estado_do_pagamento = "Pago"
            payment.montante = price
            payment.registoid = registo
            payment.save()
            return redirect('../../../')
    else:
        form = PaymentModelForm()

    
    context ={
        'form': form,
        'price': price,
    }
    return render(request, "payment.html", context)

class OptionsView(TemplateView):
    template_name = "options.html"

class PaymentOptionsView(TemplateView):
    template_name = "pay_options.html"


def emit_fatura_view(request, id):
    payment=Pagamento.objects.get(id=id)
    newFatura = Fatura()

PaymentManagement/templates/cancel.html
<html>

<head>
    <title>Checkout canceled</title>
</head>

<body>
    <section>
        <p>Forgot to add something to your cart? <a href="{% url 'home' %}">Try again</a></p>
    </section>
</body>

</html>

PaymentManagement/templates/contratos.html
{# tutorial/templates/tutorial/people.html #}
{% load render_table from django_tables2 %}
<!doctype html>
<html>
<head>
    <style>
        table {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }
        
        td, th {
          border: 1px solid #dddddd;
          text-align: left;
          padding: 8px;
        }
        
        tr:nth-child(even) {
          background-color: #dddddd;
        }
        </style>
<title>List of persons</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
</head>
    <body>
        {% render_table table%}
    </body>
    <a class="btn btn-info btn-sm" href="{% url 'PaymentManagement:options' %}">Voltar à página principal</a>
</html>

PaymentManagement/templates/delete_confirmation.html
<form method="POST"> {% csrf_token %}
    <p>Quer mesmo apagar o contrato?</p>
    <input type="submit" value="Sim"/>
</form>
<a href={% url 'PaymentManagement:contrato-list' %}><button>Não</button></a>
<a class="btn btn-info btn-sm" href="{% url 'PaymentManagement:options' %}">Voltar à página principal</a>

PaymentManagement/templates/detail.html
<a class="btn btn-info btn-sm" href="{% url 'PaymentManagement:options' %}">Voltar à página principal</a>
<p><b>Nome do cliente:</b> {{contrato.clienteid.nome}}</p>
<p><b>Nome do parque:</b> {{contrato.parqueid.nome}}</p>
<p><b>Data de início do contrato:</b> {{contrato.data_de_inicio}}</p>
<p><b>Data de término do contrato:</b> {{contrato.data_de_termino}}</p>
<p><b>Periodicidade:</b> {{contrato.periodicidadeid.periodicidade}}</p>
    {% if contrato.periodicidadeid.periodicidade == "semanal"%}
    <p><b>Dias:</b>
    {% for dia in dias %}
    {{dia.nome}},
    {% endfor %}
    {% endif %}</p>
<p><b>Lugar:</b> {{lugar.numero_do_lugar}}</p>
<p><b>Matricula:</b> {{contrato.matricula}}</p>
<a class="btn btn-info btn-sm" href={% url 'PaymentManagement:contrato-delete' id=contrato.id %}>Delete</a>

PaymentManagement/templates/edit.html
<a class="btn btn-info btn-sm" href="{% url 'PaymentManagement:contrato-update' id=record.id %}">Editar</a>

PaymentManagement/templates/fatura_create.html
<form method="POST"> {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save"/>
</form>
<a class="btn btn-info btn-sm" href="{% url 'PaymentManagement:options' %}">Voltar à página principal</a>

PaymentManagement/templates/list.html
{% extends 'table.html' %}

{% block table_class %}is-hoverable{% endblock table_class %}

{% block seta_th %}
    <th width="40px"></th>
{% endblock seta_th %}

{% block seta_tr %}
    <td class="chevron-cell"><a role="button"><span class="icon"><i class="mdi mdi-chevron-right mdi-24px"></i></span></a>
</td>
{% endblock seta_tr %}

{% block detail %}
    <tr class="detail">
        <td colspan="{{ table.columns|length|add:'1' }}" style="border-collapse: separate;">
            <div class="detail-container">
                <div style="font-size: 15px;">
                    {% block details_content %}
                    {% endblock details_content %}
                </div>
            </div>
        </td>
    </tr>
{% endblock detail %}

{% block scripts %}
<script>
    $('.main-table > tbody > tr:not(.detail)').click(function (e) {
        $('.main-table > tbody > tr.detail').not($(this).next()).removeClass('is-active');
        $('.main-table > tbody > tr:not(.detail)').not($(this)).find('td.chevron-cell .icon').removeClass('is-expanded');
        $(this).next().toggleClass('is-active');
        $(this).find('td.chevron-cell .icon').toggleClass('is-expanded');
    })
</script>
{% endblock scripts %}

{% block style %}
<style>
    .main-table > tbody > tr:not(.detail) {
        cursor: pointer;
    }

    .main-table > tbody > tr.detail {
        box-shadow: inset 0 1px 3px #dbdbdb;
        background: #fafafa;
        background-color: rgb(250, 250, 250);
    }

    .main-table > tbody > tr.detail .detail-container {
        padding: 1rem;
    }

    .main-table > tbody > tr.detail:hover {
        background-color: #fafafa !important;
    }

    .main-table > tbody > tr.detail:not(.is-active) {
        display: none;
    }

    .main-table > tbody > tr.detail .is-active {
        display: block;
    }

    .icon.is-expanded {
        transform: rotate(90deg);
    }

    .icon {
        transition: transform 150ms ease-out, opacity 86ms ease-out;
    }
</style>
{% endblock style %}

PaymentManagement/templates/pagamentos.html
<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
    <body>
        <table>
            <tr>
              <th>Montante</th>
              <th>Estado</th>
              <th>Tipo</th>
              <th>Fatura</th>
            </tr>
        {% for pagamento in object_list %}
            <tr>
                <td>{{pagamento.montante}}</td>
                <td>{{pagamento.estado_do_pagamento}}</td>
                {% if pagamento.contratoid %}
                    <td>Contrato {{pagamento.contratoid.id}}</td>
                {% endif %}
                {% if pagamento.reservaid %}
                    <td>Reserva {{pagamento.reservaid.id}}</td>
                {% endif %}
                {% if pagamento.registoid %}
                    <td>Registo {{pagamento.registoid.id}}</td>
                {% endif %}
                {% if pagamento.id in faturas %}
                    <td><a class="btn btn-info btn-sm" href="{% url 'PaymentManagement:fatura' %}">Ver Fatura</a></td>
                {% else %}
                    <td><a class="btn btn-info btn-sm" href="{% url 'PaymentManagement:fatura-emit' id=pagamento.id %}">Emitir Fatura</a></td>
                {% endif %}

            </tr>
        {% endfor %}
    </body>
    <a class="btn btn-info btn-sm" href="{% url 'PaymentManagement:options' %}">Voltar à página principal</a>
</html>

PaymentManagement/templates/parque.html
<h1>Escolha o parque onde quer criar o contrato</h1>
{% for parque in parques %}
    <button><a class="btn btn-info" href="{% url 'PaymentManagement:contrato-create' id=parque.id %}">{{parque.nome}}</a></button>
{% endfor %}
<a class="btn btn-info btn-sm" href="{% url 'PaymentManagement:options' %}">Voltar à página principal</a>

PaymentManagement/templates/payment.html
{% block content %}
<form method="POST"> {% csrf_token %}
    {{form.as_p}}
    <p>{{price}}€</p>
    <input type="submit" value="Save"/>
</form>
{% endblock %}
<a class="btn btn-info btn-sm" href="{% url 'PaymentManagement:options' %}">Voltar à página principal</a>

PaymentManagement/templates/payment_prove.html
<form method = 'POST' class="col s12" enctype="multipart/form-data">
 
    {% csrf_token %}

    {{new_form.as_p}}

<!--Below is our main file upload input -->
    <input type = "file" name = 'document'>
    <p><button type = "submit" class = "waves-effect waves-light btn" style = "background-color: teal">Publish</button></p>
</form>
<a class="btn btn-info btn-sm" href="{% url 'PaymentManagement:options' %}">Voltar à página principal</a>

PaymentManagement/templates/reclamacao_create.html
{% block content %}
<form method="POST"> {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save"/>
</form>
{% endblock %}
<a class="btn btn-info btn-sm" href="{% url 'PaymentManagement:options' %}">Voltar à página principal</a>

PaymentManagement/templates/reclamacao_list.html
<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
    <body>
        <table>
            <tr>
              <th>Reclamação</th>
              <th>Número da Fatura</th>
              <th>Alerar Fatura<th>
            </tr>
        {% for reclamacao in object_list %}
            <tr>
                <td>{{reclamacao.reclamacao}}</td>
                <td><a class="btn btn-info btn-sm" href="{% url 'PaymentManagement:fatura' %}">Ver Fatura</a></td>
                <td><a class="btn btn-info btn-sm" href="{% url 'PaymentManagement:fatura-process' id=reclamacao.faturaid.id%}">Alterar</a></td>
            </tr>
        {% endfor %}
    </body>
    <a class="btn btn-info btn-sm" href="{% url 'PaymentManagement:options' %}">Voltar à página principal</a>
</html>

PaymentManagement/templates/success.html
<html>

<head>
    <title>Thanks for your order!</title>
</head>

<body>
    <section>
        <p>
            We appreciate you gave us a chance and made a purchase on our website.
        </p>
        <a href="{% url 'home' %}">Test again</a>
    </section>
</body>

</html>